version: 2.1

commands:
  cleanup:
    description: "Cleanup directory after work"
    steps:
      - run:
          name: "Remove everything"
          command: |
            ls -A1 | xargs rm -rf

jobs:
  Get-Code:
    machine:
      image: ubuntu-2004:current
      docker_layer_caching: true
    steps:
      - checkout
      - run: |
          ls -ahl
      - cleanup
      - run: |
          ls -ahl
          echo "Done"

workflows:
  GO:
    jobs:
      - Get-Code
